### ISSUE TITLE
Unable to use SummitAST in Separate Application

### ISSUE THREAD

**Issue by mitchspano** [google/summit-ast#46]
## Expected Behavior
I should be able to use Bazel to build an application which uses Summit-AST as a dependency and use the files internally within my custom application.

## Actual Behavior
I encounter a runtime error when trying to call `SummitAST.parseAndTranslate` in a separate program.

Now, this could just be my lack of Kotlin knowledge showing, so I will keep trying to figure this one out, but I figured it best to at least create the issue to track my efforts here.

Is there a better or more canonical way to produce the AST for a `.cls` or `.trigger` file from a given file path?

## Steps to Reproduce the Problem

```
.
├── BUILD
├── MODULE.bazel
├── MODULE.bazel.lock
├── WORKSPACE
└── src
    └── main
        └── java
            └── com
                └── app
                    ├── ASTParser.java
                    ├── BUILD
                    └── Runner.java
```
`BUILD`
```
java_binary(
    name = "astparser",
    runtime_deps = ["//src/main/java/com/app:apexparser-runner"],
    main_class = "com.app.Runner",
)
```

`src/main/java/com/app/BUILD`
```
java_library(
    name = "maven_deps",
    exports = [
        "@maven//:com_google_summit_summit_ast"
    ],
    visibility = ["//visibility:public"],
)

java_library(
    name = "apexparser-runner",
    srcs = [
        "ASTParser.java",
        "Runner.java",
    ],
    deps = [
        ":maven_deps",
    ],
    visibility = ["//visibility:public"],
)
```
`Runner.java`

```java
public static void main(String[] args) {
  new ASTParser().parse(args[0]);
}
```
`ASTParser.java`
```java
package com.app;

import java.nio.file.Paths;
import com.google.summit.SummitAST;
import com.google.summit.ast.CompilationUnit;

public class ASTParser {
    public void parse(String path) {
        CompilationUnit result = SummitAST.parseAndTranslate(Paths.get(path)); // this errors out
    }
}
```

```
bazel run :astparser foo/bar.cls
```

Error Message: 
> error: non-static method parseAndTranslate(Path) cannot be referenced from a static context
CompilationUnit result = SummitAST.parseAndTranslate(Paths.get(path));

Then if I update the code to instantiate an object
```java
CompilationUnit result = new SummitAST().parseAndTranslate(Paths.get(path));
```
I get this:
>error: SummitAST() has private access in SummitAST
CompilationUnit result = new SummitAST().parseAndTranslate(Paths.get(path));

## Specifications

- Version: Bazel v 7.0.0
- Platform: Mac OS 13.3.1 (a)

**Comment by adangel** [comment]
We use it in PMD like this:

```java
        try {
            astRoot = SummitAST.INSTANCE.parseAndTranslate(task.getFileId().getOriginalPath(), task.getTextDocument().getText().toString(), null);
        } catch (SummitAST.ParseException e) {
            throw new ParseException(e);
        }
```
(https://github.com/pmd/pmd/blob/035909ca367c5ddfc6b238606c7c95da0779f1c3/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParser.java#L35-L39)

There is a static `INSTANCE` field, that you need to use. It seems, this is generated by kotlin, because of `object SummitAST` declaration.

**Comment by mitchspano** [comment]
Thanks @adangel - that was indeed the issue. Kotlin is definitely not my strong suite; I was unaware of this consequence of the `object` definition.

Also, if you need any help finishing the conversion for PMD to work with SummitAST, I would be glad to help!
