### ISSUE TITLE
Next release 2.3.0?

### ISSUE THREAD

**Issue by adangel** [google/summit-ast#63]
Hi @aaronhurst-google ,

we are going to release the next PMD version this Friday.
It would be awesome, if we could update the apex parser and fix some issues (https://github.com/pmd/pmd/issues/4922 and https://github.com/pmd/pmd/issues/5055).

Could you please release a new version of summit-ast?

Thanks!

**Comment by aaronhurst-google** [comment]
I was working on it this morning.  Will have it out today.On Jun 23, 2024, at 12:39 PM, Andreas Dangel ***@***.***> wrote:﻿
Hi @aaronhurst-google ,
we are going to release the next PMD version this Friday.
It would be awesome, if we could update the apex parser and fix some issues (pmd/pmd#4922 and pmd/pmd#5055).
Could you please release a new version of summit-ast?
Thanks!

**Comment by adangel** [comment]
Thank you! :bow: :tada: :partying_face:
